kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: appName
spec:
  replicas:
  template:
    metadata:
      name: appName
      labels:
        app: projectName
        role: appName
    spec:
      containers:
      - name: appName
        image: NODEIP:30083/CONTAINERNAME
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: appPort
